title: Mohtasham Sayeed Mohiuddin
email: mohtasham.sayeed@gmail.com
description: "Cloud Engineer with a proven track record of designing, implementing, and securing cloud solutions on AWS and GCP."
baseurl: ""
url: "https://mohtasham9.github.io/"
linkedin_username: mohtasham09
github_username: mohtasham9
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social media links
social_links:
  linkedin: https://www.linkedin.com/in/mohtasham09
  github: https://github.com/mohtasham9
  medium: https://medium.com/@mohtasham9
